# Generated by Django 5.1.1 on 2024-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinorPlanetBody',
            fields=[
                ('asteroid_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('asteroid_name', models.CharField(max_length=255)),
                ('flags_short', models.CharField(max_length=127)),
                ('attributes', models.CharField(max_length=127)),
                ('magnitude', models.FloatField()),
                ('radius_a', models.FloatField()),
                ('radius_p', models.FloatField()),
                ('inclination', models.FloatField()),
                ('mean_anomaly', models.FloatField()),
                ('argument_perihelion', models.FloatField()),
                ('asc_node_longitude', models.FloatField()),
                ('mean_daily_motion', models.FloatField()),
            ],
        ),
    ]
